### ISSUE TITLE
Task :stripe_stripe-react-native:compileDebugKotlin

### ISSUE THREAD

**Issue by dsingh-rbi** [stripe/stripe-react-native#1147]
**Describe the bug**
`Task :stripe_stripe-react-native:compileDebugKotlin FAILED`

```
* What went wrong:
Execution failed for task ':stripe_stripe-react-native:compileDebugKotlin'.
> Compilation error. See log for more details
```

**To Reproduce**
1. `npx react-native run-android`

**Expected behavior**
After running the `npx react-native run-android` the app should run successfully 

**Desktop :**
 - OS: macOS Monterey (12.6)

**Smartphone :**
 - Device: Pixel 4
 - OS: Android

**Additional context**

`"@stripe/stripe-react-native": "0.19.0"`

android/build.gradlew
```
ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        kotlinVersion = "1.5.20"
    }
```

**Comment by charliecruzan-stripe** [comment]
> Compilation error. See log for more details

Please investigate the logs to see what the issue might be, you can share them here if you're looking for more help but first thing would be to search for the specific error message in the logs and use that to search through other issues here or on Stack Overflow maybe. Closing since this likely isn't a bug with the SDK but will reopen if more info is provided that hints that this could be a bug in the SDK

**Comment by dsingh-rbi** [comment]
My Apologies, 

it was a issue related to the `KotlinVersion`. I have to use the latest version to compile it successfully.

**Comment by hugoh59** [comment]
How did you fix this exactly @dsingh-rbi  ?

**Comment by mikhail-shekhtman** [comment]
I stumbled upon same behavior when updated version of strip library to 0.23.1 and version of kotlin to 1.8.0. 

It complains on when statements throwing compilation error: https://youtrack.jetbrains.com/issue/KT-44705

to fix it, downgrade kotlin version to 1.7.21, where it is still a warning.
