### ISSUE TITLE
CardField error thrown on RN0.62 after upgrading to 0.1.5

### ISSUE THREAD

**Issue by ghitier** [stripe/stripe-react-native#440]
**Describe the bug**
An error is thrown when the CardField component gets unmounted.

**To Reproduce**
1. Use RN version 0.62.3 or below
2. Use v0.1.5 of stripe-react-native
3. Use the CardField component
4. Make the CardField component unmount (in my case navigating to another screen for ex)
5. There should be an error thrown: `TextInputState.currentlyFocusedInput() is not a function` *(iOS)*, `undefined is not a function` *(Android)*.

**Expected behavior**
No error to be thrown.

**Screenshots**
~~If applicable, add screenshots to help explain your problem.~~

**Desktop:**
 - OS: MacOS
 - Version: Big Sur

**React Native:**
- Version: 0.62.3

**Smartphone:**
 - Device: iPhone6
 - OS: iOS
 - Version: 12

**Additional context**
The TextInputState **currentlyFocusedInput** method was introduced in RN0.63. Previously, the **currentlyFocusedField** method had to be used.

On my end I'm trying to patch this by using the old method. It would be nice if the library could support both though.

**Comment by erikhu** [comment]
i have the same problem, do you resolve it? @ghitier

**Comment by ghitier** [comment]
@erikhu No, unfortunatly, I gave up for now and rolled back to 0.1.4. I'll probably upgrade my RN soon, so I'm not sure if I'll give it another try.

**Comment by arekkubaczkowski** [comment]
@ghitier @erikhu good news, this will be fixed from the next release

**Comment by erikhu** [comment]
@arekkubaczkowski thank you for the news! i solved it upgrading the project to latest react native version
