### ISSUE TITLE
CardField crashes the app when it's focused and unmounted while using the new architecture (Fabric)

### ISSUE THREAD

**Issue by aganov** [stripe/stripe-react-native#1732]
Using the new NEW_ARCH (Fabric), the app crashes with the error: `Swift runtime failure: force unwrapped a nil value + 0 [inlined] closure #1 in CardFieldManager.blur(_:) + 484` when the component containing `CardField` is unmounted while the `CardField` is focused.

**To Reproduce**
1. Create a screen with a `CardField` component and compile the iOS app with `RCT_NEW_ARCH_ENABLED=1`.
2. Focus on the `CardField`.
3. Unmount the screen (e.g., using `navigation.goBack`, `bottomsheet.close`, etc.).
4. See the crash.

**Expected behavior**
The app should dismiss keyboard and unmount the screen without crashing, even when the `CardField` is focused.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: N/A
 - Version: N/A

**Smartphone (please complete the following information):**
 - Device: iPhone15
 - OS: iOS 18.5
 - Browser: N/A
 - Version: N/A

**Additional context**
This issue occurs only when using the new Fabric architecture with `RCT_NEW_ARCH_ENABLED=1`. I have not tested on Android yet, the issue may also be present there.

**Comment by griffinshuth** [comment]
Android does not even show the CardField with Fabric enabled.  This is a huge issue since react native 76 which is coming out next month will have the new Architecture enabled by default which will make this library unusable at that point.  @charliecruzan-stripe any update on supporting Fabric?
![Screenshot 2024-09-24 at 12 23 37 PM](https://github.com/user-attachments/assets/1f72434b-e676-4009-a207-609fd46ddacd)

**Comment by iM-GeeKy** [comment]
@davidme-stripe @charliecruzan-stripe is there any update on this? New arch support appears to be landing soon and this is one issue we are seeing in our preparations.

**Comment by griffinshuth** [comment]
any update on this react native 0.76.0 was just released today with the New Arch turned on by default and this library does not work with it are you guys going to update it?

**Comment by angelica-snowit** [comment]
any update?

**Comment by FladioArmandika** [comment]
any update?

**Comment by Jleban** [comment]
any update ? This is very problematic

**Comment by iM-GeeKy** [comment]
Is there a patch we can apply temporarily until this issue is resolved? @tjclawson-stripe @ianjabour-stripe @charliecruzan-stripe

**Comment by sajorahasan** [comment]
Faced the same issue, and its keeping us from migrating to new architecture.

**Comment by firasrashidi** [comment]
Any updates?

**Comment by tjclawson-stripe** [comment]
Hi all, thanks for reporting. We're working on updating to the new architecture and will post an update when completed.

**Comment by firasrashidi** [comment]
Thank you, any timeline though?

**Comment by sajorahasan** [comment]
Any update on this?

**Comment by RepoCheyo** [comment]
hi trying to implement add card functionality to react native app, the thing here its that only with navigation going back or closing the component where the CardField its inside whether is focused or has been focused once it crashes in auto the app. Tried using inside react navigation lib the method navigate.popToTop it works but the going back should be the correct way.

**Comment by haris18896** [comment]
is there any update on this, On ios my app crashes when I close the bottomSheet or navigate to another screen, and on android I'm not getting the cardDetails in the callback function onCardChange

**Comment by glopez-askit** [comment]
Same issue, is this library still maintained?

**Comment by joix97b** [comment]
same issue @tjclawson-stripe , could you estimate time of new architecture support?

**Comment by emeliepetersson** [comment]
Any update on this?

**Comment by 4everman** [comment]
any update?

**Comment by sajorahasan** [comment]
Stripe is the only package that is keeping us from migrating to the new architecture currrently.

**Comment by ivan-moego** [comment]
Same issue

**Comment by dlato97** [comment]
any update?

**Comment by bilal2k21** [comment]
### **This solution worked for me**

To fix the issue by patching the Stripe React Native package in your node_modules directory, follow these steps:

First, install the patch-package:

npm install --save-dev patch-package

Now, you need to modify the problematic file in your node_modules directory. Navigate to:

cd node_modules/@stripe/stripe-react-native/ios/CardFieldManager.swift

Open this file in a text editor and find the blur function. It should look like:

@objc func blur(_ reactTag: NSNumber) {
    self.bridge!.uiManager.addUIBlock { (_: RCTUIManager?, viewRegistry: [NSNumber: UIView]?) in
        let view: CardFieldView = (viewRegistry![reactTag] as? CardFieldView)!
        view.blur()
    }
}

Replace it with the safer version:

@objc func blur(_ reactTag: NSNumber) {
    self.bridge!.uiManager.addUIBlock { (_: RCTUIManager?, viewRegistry: [NSNumber: UIView]?) in
        guard let viewRegistry = viewRegistry, let view = viewRegistry[reactTag] as? CardFieldView else {
            NSLog("[StripeSdk] Invalid view or reactTag when calling blur. \(reactTag)")
            return
        }
        view.blur()
    }
}

Save the file.
Now create the patch:

npx patch-package @stripe/stripe-react-native

This will create a patch file in the patches directory of your project. The file will be named something like @stripe+stripe-react-native+0.x.x.patch.
Add a postinstall script to your package.json to apply the patch automatically when dependencies are installed:

"scripts": {
  "postinstall": "patch-package"
}

Rebuild your iOS app:

cd ios
pod install
cd ..
npx react-native run-ios
This approach has several advantages:

Your changes won't be lost when you reinstall dependencies
The patch can be shared with your team
It's a cleaner approach than modifying files directly in the Pods directory

The patch-package tool will create a diff of your changes and apply them whenever the dependencies are installed, ensuring the fix is consistently applied.

**Comment by ivan-moego** [comment]
> ### **这个解决方案对我有用**
> 要通过修补 node_modules 目录中的 Stripe React Native 包来解决此问题，请按照以下步骤操作：
> 
> 首先，安装补丁包：
> 
> npm install --save-dev 补丁包
> 
> 现在，您需要修改 node_modules 目录中有问题的文件。导航至：
> 
> cd node_modules/@stripe/stripe-react-native/ios/CardFieldManager.swift
> 
> 在文本编辑器中打开此文件并找到模糊函数。它应该如下所示：
> 
> [@objc](https://github.com/objc)func blur(_ reactTag: NSNumber) { self.bridge!.uiManager.addUIBlock { (_: RCTUIManager?, viewRegistry: [NSNumber: UIView]?) 在 let view: CardFieldView = (viewRegistry![reactTag] as? CardFieldView)! view.blur() } }
> 
> 用更安全的版本替换它：
> 
> [@objc](https://github.com/objc)func blur(_ reactTag: NSNumber) { self.bridge!.uiManager.addUIBlock { (_: RCTUIManager?, viewRegistry: [NSNumber: UIView]?) in guard let viewRegistry = viewRegistry, let view = viewRegistry[reactTag] as? CardFieldView else { NSLog([S​​tripeSdk] 调用 blur 时视图或 reactTag 无效。 (reactTag)") return } view.blur() } }
> 
> 保存文件。 现在创建补丁：
> 
> npx 补丁包@stripe/stripe-react-native
> 
> 这将在项目的补丁目录中创建一个补丁文件。该文件的名称类似于[@stripe](https://github.com/stripe)+stripe-react-native+0.xxpatch. 将 postinstall 脚本添加到你的 package.json，以便在安装依赖项时自动应用补丁：
> 
> “脚本”：{ “postinstall”：“补丁包” }
> 
> 重建你的 iOS 应用程序：
> 
> cd ios pod install cd .. npx react-native run-ios 这种方法有几个优点：
> 
> 重新安装依赖项时，您的更改不会丢失。 补丁可以与您的团队共享。 这比直接在 Pods 目录中修改文件更简洁。
> 
> patch-package 工具将创建您更改的差异，并在安装依赖项时应用它们，确保一致地应用修复。

This is also how I've modified it for now. But this only avoids crashes, and the CardField won't automatically focus the cursor anymore.

**Comment by sfriedman-stripe** [comment]
Hi all, thank you for sharing all of the feedback here. I agree with you; it's taken us way too long to support the new architecture. I'm sorry for that. Fortunately, I have good news: we have begun our work to start migrating to the new architecture over the past couple of weeks and hope to complete it over the next 4-6 weeks. If anything changes, you can expect to see an update from me here, but I'm optimistic we should be able to complete it by then.

I apologize again for the delay and look forward to getting this shipped for you all soon. Please keep the feedback coming as well; we will do a better job at communicating with you all in GitHub issues going forward.

**Comment by ivan-moego** [comment]
@sfriedman-stripe any update?

**Comment by sfriedman-stripe** [comment]
Hoping to land this this week or next week

**Comment by sfriedman-stripe** [comment]
Hi all, we're excited to share that support for the new architecture was released yesterday as v0.45.0 (fixed in https://github.com/stripe/stripe-react-native/pull/1893)! 🎉 Thank you again for your patience.

If anyone is still experiencing this after upgrading to v0.45.0, could you please let us know? Otherwise we will close this issue as resolved

**Comment by ivan-moego** [comment]
I upgraded to v0.45.0. No issues were found on iOS, but the Android compilation failed with an error like this: "node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/utils/Mappers.kt:1043:29 Class 'kotlin.Unit' was compiled with an incompatible version of Kotlin. The actual metadata version is 2.1.0, but the compiler version 1.9.0 can read versions up to 2.0.0."
Currently, I'm using Expo 52, and it seems that it doesn't support upgrading to Kotlin 2.0.0 yet. What other solutions are there?

**Comment by sabuhiteymurov** [comment]
I got these build errors after upgrading to version `0.45.0`. I'm using Expo sdk 52: 

/Users/expo/workingdir/build/ios/Pods/StripePayments/StripePayments/Source/Helpers/BundleLocator.swift:10:41: error: cannot find 'BundleLocatorProtocol' in scope ``` open class StripePaymentsBundleLocator: BundleLocatorProtocol ```

/Users/expo/workingdir/build/ios/Pods/StripePayments/StripePayments/Source/Helpers/BundleLocator.swift:10:8: error: cannot find 'StripePaymentsBundleLocator' in scope ```open class StripePaymentsBundleLocator: BundleLocatorProtocol```

**Comment by gleung93** [comment]
After upgrading to `0.45.0` I get build errors on both iOS and Android using Expo SDK 52

Android:
```
Execution failed for task ':stripe_stripe-react-native:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
```

iOS:
```
❌  Undefined symbols for architecture x86_64
┌─ Symbol: _EmbeddedPaymentElementViewCls
└─ Referenced from: _RCTThirdPartyFabricComponentsProvider in libReact-RCTFabric.a[41](RCTThirdPartyFabricComponentsProvider.o)
```

**Comment by jsSteud** [comment]
> After upgrading to `0.45.0` I get build errors on both iOS and Android using Expo SDK 52
> 
> Android:
> 
> ```
> Execution failed for task ':stripe_stripe-react-native:compileDebugKotlin'.
> > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
> ```
> 
> iOS:
> 
> ```
> ❌  Undefined symbols for architecture x86_64
> ┌─ Symbol: _EmbeddedPaymentElementViewCls
> └─ Referenced from: _RCTThirdPartyFabricComponentsProvider in libReact-RCTFabric.a[41](RCTThirdPartyFabricComponentsProvider.o)
> ```

I get the same, but for ```arm64```

**Comment by emeliepetersson** [comment]
> Undefined symbols

I get this error as well

**Comment by vincentracine** [comment]
Same issue here `"@stripe/stripe-react-native": "^0.45.0"` with `"expo": "~52.0.11"`. Targeting iOS 18 physical device.

```
❌  Undefined symbols for architecture arm64
┌─ Symbol: _EmbeddedPaymentElementViewCls
└─ Referenced from: _RCTThirdPartyFabricComponentsProvider in libReact-RCTFabric.a[41](RCTThirdPartyFabricComponentsProvider.o)
```
