### ISSUE TITLE
Support Recent Version of React Native.

### ISSUE THREAD

**Issue by ponikar** [stripe/stripe-react-native#1284]
**Describe the bug**
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stripe_stripe-react-native:compileDebugKotlin'.
> Compilation error. See log for more details

I saw a similar issue and upgraded my `react-native` project. 

I was having `0.63` version earlier it took a week to upgrade the react-native version to `0.68`. It is an expo bare workflow. The latest version of this library is not working with the recent version of react-native which I belive most of the apps are running.

I am not sure should I upgrade my react-native project to the latest one, It is a long process and we don't have that much bandwidth. 

In android, we can use the older version but in iOS it is not working with Xcode 14.

So please make the library work with a version later than `0.67`

**Comment by kaialsh705** [comment]
Same error please help me.

**Comment by talaikis** [comment]
> So please make the library work with a version later than `0.67`

What's completed about this?

**Comment by AstrOOnauta** [comment]
Into `android/build.gradle`, I just updated my `kotlinVersion` and `kotlin_version` from `1.6.21` to `1.8.0`.

My project is RN Cli:
 - React Native v0.71.13;
 - @stripe/stripe-react-native v 0.35.0.
