### ISSUE TITLE
not working with react native 0.75.2 !

### ISSUE THREAD

**Issue by burakkbilginn** [stripe/stripe-react-native#1718]
**Describe the bug**
When I add @stripe/stripe-react-native library, and run with yarn android, the error comes  
`> Task :stripe_stripe-react-native:compileDebugKotlin FAILED`
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':stripe_stripe-react-native:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BU�LD FAILED in 40s
error Failed to install the app. Command failed with exit code 1: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081
e: file:///C:/Users/BURAK/Desktop/react/social/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/GooglePayButtonManager.kt:7:50 Type argument is not within its bounds: should be subtype of 'View' e: file:///C:/Users/BURAK/Desktop/react/social/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/GooglePayButtonManager.kt:12:3 'onAfterUpdateTransaction' overrides nothing e: file:///C:/Users/BURAK/Desktop/react/social/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt:884:61 Java type mismatch expected (Mutable)Map<(raw) Any?, (raw) Any?>! but found HashMap<String, Any>. Use explicit cast e: file:///C:/Users/BURAK/Desktop/react/social/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/StripeSdkModule.kt:899:61 Java type mismatch expected (Mutable)Map<(raw) Any?, (raw) Any?>! but found HashMap<String, Any>. Use explicit cast e: file:///C:/Users/BURAK/Desktop/react/social/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/pushprovisioning/AddToWalletButtonManager.kt:12:81 Type argument is not within its bounds: should be subtype of 'View' e: file:///C:/Users/BURAK/Desktop/react/social/node_modules/@stripe/stripe-react-native/android/src/main/java/com/reactnativestripesdk/pushprovisioning/AddToWalletButtonManager.kt:16:3 'onDropViewInstance' overrides nc/main/java/com/reactnativestripesdk/pushprovisioning/AddToWalletButtonManager.kt:21:3 'onAfterUpdateTransaction' overrides nothing FAILURE: Build failed with an exception. * What went wrong: Execution failed for task ':stripe_stripe-react-native:compileDebugKotlin'. > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction > Compilation error. See log for more details * Try: > Run with --stacktrace option to get the stack trace. > Run with --info or --debug option to get more log output. > Run with --scan to get full insights. > Get more help at https://help.gradle.org. BU�LD FAILED in 40s.
info Run CLI with --verbose flag for more details.
```

**To Reproduce**

**Expected behavior**
Run without any error, as before in version 0.73.2 of react native.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Smartphone (please complete the following information):**

**Additional context**

**Comment by iM-GeeKy** [comment]
Duplicate of https://github.com/stripe/stripe-react-native/issues/1713

**Comment by charliecruzan-stripe** [comment]
closing as duplicate
