### PR TITLE
Unsupported text input method

### LINKED ISSUE #440: CardField error thrown on RN0.62 after upgrading to 0.1.5
**Describe the bug**
An error is thrown when the CardField component gets unmounted.

**To Reproduce**
1. Use RN version 0.62.3 or below
2. Use v0.1.5 of stripe-react-native
3. Use the CardField component
4. Make the CardField component unmount (in my case navigating to another screen for ex)
5. There should be an error thrown: `TextInputState.currentlyFocusedInput() is not a function` *(iOS)*, `undefined is not a function` *(Android)*.

**Expected behavior**
No error to be thrown.

**Screenshots**
~~If applicable, add screenshots to help explain your problem.~~

**Desktop:**
 - OS: MacOS
 - Version: Big Sur

**React Native:**
- Version: 0.62.3

**Smartphone:**
 - Device: iPhone6
 - OS: iOS
 - Version: 12

**Additional context**
The TextInputState **currentlyFocusedInput** method was introduced in RN0.63. Previously, the **currentlyFocusedField** method had to be used.

On my end I'm trying to patch this by using the old method. It would be nice if the library could support both though.

### PR DESCRIPTION
**Pull request by arekkubaczkowski**
resolves #440 

this fix resolves issue which throws exception if certain TextInputState methods are not available since it has been added from 
 react-native 0.63x.

### CODE REVIEW

**Review by thorsten-stripe — APPROVED** [review]
LGTM, thanks

**Comment by erikhu** [comment]
@arekkubaczkowski amazing! thank you so much
