### ISSUE TITLE
Importing `jest/mock.js` causes tests to fail

### ISSUE THREAD

**Issue by simon-abbott** [stripe/stripe-react-native#2338]
**Describe the bug**
After updating to 0.59.x our tests started failing with the error "Cannot find module './src/specs/NativeStripeSdkModule' from 'node_modules/@stripe/stripe-react-native/jest/mock.js'"

**To Reproduce**
1. Install @stripe/stripe-react-native v0.59.0 or later
2. Follow the [Jest setup instructions](https://github.com/stripe/stripe-react-native#testing)
3. Run Jest

**Expected behavior**
The tests should work properly

**Screenshots**
N/A

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
This seems to be due to the `jest.mock` call introduced in https://github.com/stripe/stripe-react-native/commit/976e5f6153afd3bedab39b7b24b72ebfeaaa5688. Changing the `jest.mock` call from `./src/specs/NativeStripeSdkModule` to `../src/specs/NativeStripeSdkModule` fixed the issue for me.

**Comment by tjclawson-stripe** [comment]
Hi @simon-abbott, thanks for flagging! This has been fixed in https://github.com/stripe/stripe-react-native/pull/2345 and will be included in the next release.
